🚨 Fix incompatible types assignment in ``main`` function signature
The following error in ``mypy`` is a result of re-assigning
``arguments``:

error: Incompatible types in assignment (expression has type
"Namespace", variable has type "Optional[List[str]]")  [assignment]

The solution is to avoid the use of the pattern that ``argparse``
suggests, because it causes type shadowing that is hard for humans and
hard for ``mypy`` to read.  The following resource does a good job
explaining the problem and solution:

https://adamj.eu/tech/2021/05/23/python-type-hints-mypy-doesnt-allow-variables-to-change-type/